In [7]:
## Nome : Gabriel Faria Monteiro
## MATRÍCULA : 757

In [8]:
from IPython.display import display
# Importando bibliotecas

#Analise de dados
import pandas as pd
import numpy as np

Valor_referencia = 85
#Tabela de dados
tabela = {
    "Sensor": [
        "Sensor S1",
        "Sensor S2",
        "Sensor S3",
        "Sensor S4",
        "Sensor S5",
        "Sensor S6",
    ],
    "Temp_Lida (°C)": [84.820, 85.150, 84.985, 85.040, 85.310, 84.910],
}

dados = pd.DataFrame(tabela)
display(dados)

      Sensor  Temp_Lida (°C)
0  Sensor S1          84.820
1  Sensor S2          85.150
2  Sensor S3          84.985
3  Sensor S4          85.040
4  Sensor S5          85.310
5  Sensor S6          84.910

In [9]:

erro_abs1 = abs(85 - 84.820)
erro_abs2 = abs(85 - 85.150 )
erro_abs3 = abs(85 - 84.985 )
erro_abs4 = abs(85 - 85.040)
erro_abs5 = abs(85 - 85.310)
erro_abs6 = abs(85 - 84.910)

tabela_errosabsoluto= {
     "Sensor" : [
         "Sensor S1",
        "Sensor S2",
        "Sensor S3",
        "Sensor S4",
        "Sensor S5",
        "Sensor S6",

     ],
    "Erro absoluto " : [ erro_abs1,erro_abs2,erro_abs3,erro_abs4,erro_abs5,erro_abs6],
 }

dados_erroabsoluto = pd.DataFrame(tabela_errosabsoluto)
display(dados_erroabsoluto)

      Sensor  Erro absoluto
0  Sensor S1           0.180
1  Sensor S2           0.150
2  Sensor S3           0.015
3  Sensor S4           0.040
4  Sensor S5           0.310
5  Sensor S6           0.090

In [10]:
erro_rel1 = erro_abs1/abs(84.820)
erro_rel2 = erro_abs2/abs(85.150)
erro_rel3 = erro_abs3/abs(84.985)
erro_rel4 = erro_abs4/abs(85.040)
erro_rel5 = erro_abs5/abs(85.310)
erro_rel6 = erro_abs6/abs(84.910)



tabela_errorelativo= {
     "Sensor" : [
         "Sensor S1",
        "Sensor S2",
        "Sensor S3",
        "Sensor S4",
        "Sensor S5",
        "Sensor S6",

     ],
    "Erro relativo " : [erro_rel1,erro_rel2,erro_rel3,erro_rel4,erro_rel5,erro_rel6],
 }

dados_errorelativo = pd.DataFrame(tabela_errorelativo)
display(dados_errorelativo)

      Sensor  Erro relativo
0  Sensor S1        0.002122
1  Sensor S2        0.001762
2  Sensor S3        0.000177
3  Sensor S4        0.000470
4  Sensor S5        0.003634
5  Sensor S6        0.001060

In [11]:
tabela_erropercentual= {
     "Sensor" : [
         "Sensor S1",
        "Sensor S2",
        "Sensor S3",
        "Sensor S4",
        "Sensor S5",
        "Sensor S6",

     ],
    "Erro percentual " : [erro_rel1*100,erro_rel2*100,erro_rel3*100,erro_rel4*100,erro_rel5*100,erro_rel6*100],
 }

dados_erropercentual= pd.DataFrame(tabela_erropercentual)
display(dados_erropercentual)

      Sensor  Erro percentual
0  Sensor S1          0.212214
1  Sensor S2          0.176160
2  Sensor S3          0.017650
3  Sensor S4          0.047037
4  Sensor S5          0.363381
5  Sensor S6          0.105995

In [12]:
dados["Erro absoluto" ] = [erro_abs1,erro_abs2,erro_abs3,erro_abs4,erro_abs5,erro_abs6]
dados["Erro relativo "] = [erro_rel1,erro_rel2,erro_rel3,erro_rel4,erro_rel5,erro_rel6]
dados["Erro percentual"] = [erro_rel1*100,erro_rel2*100,erro_rel3*100,erro_rel4*100,erro_rel5*100,erro_rel6*100]
display(dados)

# #ou
# dados["Erro absoluto "] = abs(dados["Temp_Lida (°C)"] - Valor_referencia)
# dados["Erro relativo "] = dados["Erro absoluto "]/abs(Valor_referencia)
# dados["Erro percentual"] = dados["Erro relativo "]*100
# display(dados)

      Sensor  Temp_Lida (°C)  Erro absoluto  Erro relativo   Erro percentual
0  Sensor S1          84.820          0.180        0.002122         0.212214
1  Sensor S2          85.150          0.150        0.001762         0.176160
2  Sensor S3          84.985          0.015        0.000177         0.017650
3  Sensor S4          85.040          0.040        0.000470         0.047037
4  Sensor S5          85.310          0.310        0.003634         0.363381
5  Sensor S6          84.910          0.090        0.001060         0.105995

In [13]:
tabela_base = {
    "Paciente" : [
        "P1",
        "P2",
        "P3",
        "P4",
        "P5",
    ],
    "Oxigênio Medido (%)" : [92.3456,98.8765,95.5555,97.4999,90.0501],
}

dados_base = pd.DataFrame(tabela_base)
display(dados_base)

  Paciente  Oxigênio Medido (%)
0       P1              92.3456
1       P2              98.8765
2       P3              95.5555
3       P4              97.4999
4       P5              90.0501

In [14]:
dados_base["Oxigênio Medido (%)"] = dados_base["Oxigênio Medido (%)"].round(2)
display(dados_base)

  Paciente  Oxigênio Medido (%)
0       P1                92.35
1       P2                98.88
2       P3                95.56
3       P4                97.50
4       P5                90.05

In [15]:
dados_base["Oxigênio Medido (%)"]  = np.trunc(dados_base["Oxigênio Medido (%)"]*10)/10
display(dados_base)

  Paciente  Oxigênio Medido (%)
0       P1                 92.3
1       P2                 98.8
2       P3                 95.5
3       P4                 97.5
4       P5                 90.0

In [16]:
dados_base["Oxigênio Medido (%)"] = dados_base["Oxigênio Medido (%)"].round(0).astype(int)
display(dados_base)

  Paciente  Oxigênio Medido (%)
0       P1                   92
1       P2                   99
2       P3                   96
3       P4                   98
4       P5                   90

Questão 1

1(F)
O erro absoluto não é independente da ordem de grandeza. Um erro absoluto de $1$ metro tem um impacto enorme se você estiver medindo o comprimento de um parafuso (onde a grandeza é milimétrica ou centimétrica), mas é insignificante se estiver medindo a distância entre duas cidades. Quem nos dá a noção do impacto em relação à ordem de grandeza é o erro relativo ou percentual.

2(V)

3(F)O erro percentual é calculado multiplicando o erro relativo por $100\%$

4(V)

5(V)

Questão 2


(especificamente nos reais não negativos, $\mathbb{R}_+$ ou $[0, +\infty[$).

Qualquer medida física obtida por um instrumento (como comprimento, temperatura, massa, tempo) é expressa por uma quantidade contínua que pode assumir valores inteiros, fracionários (racionais) ou com infinitas casas decimais não periódicas. O conjunto dos Números Reais engloba perfeitamente todas essas possibilidades de medidas físicas.

Os naturais e inteiros são muito restritos, pois ignoram os valores decimais e frações que qualquer medição real com boa precisão costuma apresentar

OS números complexos não fazem sentido físico para medidas de grandezas macroscópicas usuais, pois introduzem a unidade imaginária ($i$), que não tem correspondência direta na leitura de um sensor ou instrumento convencional